# -*- coding: utf-8 -*-
"""Deep_Learning_Assignment_3_2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZNtofM7cuI52xPZBl0FUUgT-nKSKsx9

# Helper Code for Assignment 3 (RNN language models)

## Reading raw text file & Create DataLoader
"""

import os

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import numpy.ma as ma

class Vocabulary:

    def __init__(self, pad_token="<pad>", unk_token='<unk>'):
        self.id_to_string = {}
        self.string_to_id = {}
        
        # add the default pad token
        self.id_to_string[0] = pad_token
        self.string_to_id[pad_token] = 0
        
        # add the default unknown token
        self.id_to_string[1] = unk_token
        self.string_to_id[unk_token] = 1        
        
        # shortcut access
        self.pad_id = 0
        self.unk_id = 1
        
    def __len__(self):
        return len(self.id_to_string)

    def add_new_word(self, string):
        self.string_to_id[string] = len(self.string_to_id)
        self.id_to_string[len(self.id_to_string)] = string

    # Given a string, return ID
    def get_idx(self, string, extend_vocab=False):
        if string in self.string_to_id:
            return self.string_to_id[string]
        elif extend_vocab:  # add the new word
            self.add_new_word(string)
            return self.string_to_id[string]
        else:
            return self.unk_id


# Read the raw txt file and generate a 1D PyTorch tensor
# containing the whole text mapped to sequence of token IDs, and a vocab object.
class TextData:

    def __init__(self, file_path, vocab=None, extend_vocab=True, device='cuda'):
        self.data, self.vocab = self.text_to_data(file_path, vocab, extend_vocab, device)
        
    def __len__(self):
        print(len(self.data))
        return len(self.data)

    def text_to_data(self, text_file, vocab, extend_vocab, device):
        """Read a raw text file and create its tensor and the vocab.

        Args:
          text_file: a path to a raw text file.
          vocab: a Vocab object
          extend_vocab: bool, if True extend the vocab
          device: device

        Returns:
          Tensor representing the input text, vocab file

        """
        assert os.path.exists(text_file)
        if vocab is None:
            vocab = Vocabulary()

        data_list = []
        num_lines=0
        number_chars=0
        capital=0
        lowcase=0


        # Construct data
        full_text = []
        print(f"Reading text file from: {text_file}")
        with open(text_file, 'r') as text:
            for line in text:
                tokens = list(line)
                num_lines+=1
                for token in tokens:
                    number_chars+=1
                    # get index will extend the vocab if the input
                    # token is not yet part of the text.
                    full_text.append(vocab.get_idx(token, extend_vocab=extend_vocab))

                    if token.isupper():
                      capital+=1
                    if token.islower():
                      lowcase+=1
        # convert to tensor
        data = torch.tensor(full_text, device=device, dtype=torch.int64)
        print("Number of lines {}".format(num_lines))
        print("Number of character {}".format(number_chars))
        print("Number of Capital Letters number {}".format(capital))
        print("Number of Lower Letters number {}".format(lowcase))
        print("Number of Unique Character {}".format(len(vocab.string_to_id)))
        print("Done.")

        return data, vocab
    

# Since there is no need for schuffling the data, we just have to split
# the text data according to the batch size and bptt length.
# The input to be fed to the model will be batch[:-1]
# The target to be used for the loss will be batch[1:]
class DataBatches:

    def __init__(self, data, bsz, bptt_len, pad_id):
        self.batches = self.create_batch(data, bsz, bptt_len, pad_id)

    def __len__(self):
        return len(self.batches)

    def __getitem__(self, idx):
        return self.batches[idx]

    def create_batch(self, input_data, bsz, bptt_len, pad_id):
        """Create batches from a TextData object .

        Args:
          input_data: a TextData object.
          bsz: int, batch size
          bptt_len: int, bptt length
          pad_id: int, ID of the padding token

        Returns:
          List of tensors representing batches

        """
        batches = []  # each element in `batches` is (len, B) tensor
        text_len = len(input_data)
        segment_len = text_len // bsz + 1

        # Question: Explain the next two lines!
        padded = input_data.data.new_full((segment_len * bsz,), pad_id)
        padded[:text_len] = input_data.data
        padded = padded.view(bsz, segment_len).t()
        num_batches = segment_len // bptt_len + 1

        for i in range(num_batches):
            # Prepare batches such that the last symbol of the current batch
            # is the first symbol of the next batch.
            if i == 0:
                # Append a dummy start symbol using pad token
                batch = torch.cat(
                    [padded.new_full((1, bsz), pad_id),
                     padded[i * bptt_len:(i + 1) * bptt_len]], dim=0)
                batches.append(batch)
            else:
                batches.append(padded[i * bptt_len - 1:(i + 1) * bptt_len])

        return batches

# downlaod the text
# Make sure to go to the link and check how the text looks like.
!wget http://www.gutenberg.org/files/49010/49010-0.txt

# This is for Colab. Adapt the path if needed.
text_path = "/content/49010-0.txt"

DEVICE = 'cuda'

batch_size = 32
bptt_len = 64

my_data = TextData(text_path, device=DEVICE)
batches = DataBatches(my_data, batch_size, bptt_len, pad_id=0)

"""## Model"""

# RNN based language model
class RNNModel(nn.Module):

    def __init__(self, num_classes, emb_dim, hidden_dim, num_layers):
        """Parameters:
        
          num_classes (int): number of input/output classes
          emb_dim (int): token embedding size
          hidden_dim (int): hidden layer size of RNNs
          num_layers (int): number of RNN layers
        """
        super().__init__()
        self.num_classes = num_classes
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        self.input_layer = nn.Embedding(num_classes, emb_dim)
        self.rnn = nn.RNN(emb_dim, hidden_dim, num_layers)
        self.out_layer = nn.Linear(hidden_dim, num_classes)

    def forward(self, input, state):
        emb = self.input_layer(input)
        output, state = self.rnn(emb, state)
        output = self.out_layer(output)
        output = output.view(-1, self.num_classes)
        return output, state

    def init_hidden(self, bsz):
        weight = next(self.parameters())
        return weight.new_zeros(self.num_layers, bsz, self.hidden_dim)


# To be modified for LSTM...
def custom_detach(h):
    return h.detach()

"""## Decoding"""

@torch.no_grad()
def complete(model, prompt, steps, sample=False):
    """Complete the prompt for as long as given steps using the model.
    
    Parameters:
      model: language model
      prompt (str): text segment to be completed
      steps (int): number of decoding steps.
      sample (bool): If True, sample from the model. Otherwise greedy.

    Returns:
      completed text (str)
    """
    model.eval()
    out_list = []
    
    # forward the prompt, compute prompt's ppl
    prompt_list = []
    char_prompt = list(prompt)
    for char in char_prompt:
        prompt_list.append(my_data.vocab.string_to_id[char])
    x = torch.tensor(prompt_list).to(DEVICE).unsqueeze(1)
    
    states = model.init_hidden(1)
    logits, states = model(x, states)
    probs = F.softmax(logits[-1], dim=-1)
        
    if sample:
        ix=torch.multinomial(probs, num_samples=1)
        
    else:
        max_p, ix = torch.topk(probs, k=1, dim=-1)

    out_list.append(my_data.vocab.id_to_string[int(ix)])
    x = ix.unsqueeze(1)
    
    # decode 
    for k in range(steps):
        logits, states = model(x, states)
        probs = F.softmax(logits, dim=-1)
        if sample:  # sample from the distribution or take the most likely
             ix=torch.multinomial(probs, num_samples=1)   
             
        else:
            _, ix = torch.topk(probs, k=1, dim=-1)
        out_list.append(my_data.vocab.id_to_string[int(ix)])
        x = ix
    return ''.join(out_list)

learning_rate = 0.0005
clipping = 1.0
embedding_size = 64
rnn_size = 2048
rnn_num_layers = 1

# vocab_size = len(module.vocab.itos)
vocab_size = len(my_data.vocab.id_to_string)
print(F"vocab size: {vocab_size}")

model = RNNModel(
    num_classes=vocab_size, emb_dim=embedding_size, hidden_dim=rnn_size,
    num_layers=rnn_num_layers)
model = model.to(DEVICE)
hidden = model.init_hidden(batch_size)

loss_fn = nn.CrossEntropyLoss(ignore_index=0)
optimizer = torch.optim.Adam(params=model.parameters(), lr=learning_rate)

"""## Training loop"""

# Training

num_epochs = 30
report_every = 30
prompt = "Dogs like best to"
perp_list=[]
gen_text=[]

for ep in range(num_epochs):
    print(f"=== start epoch {ep} ===")
    state = model.init_hidden(batch_size)
    for idx in range(len(batches)):
        batch = batches[idx]
        model.train()
        optimizer.zero_grad()
        state = custom_detach(state)
        
        input = batch[:-1]
        target = batch[1:].reshape(-1)

        bsz = input.shape[1]
        prev_bsz = state.shape[1]
        if bsz != prev_bsz:
            state = state[:, :bsz, :]
        output, state = model(input, state)
        loss = loss_fn(output, target)
        perp=torch.exp(loss)
        perp_list.append(perp)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), clipping)
        optimizer.step()
        if idx % report_every == 0:
            # print(f"train loss: {loss.item()}")  # replace me by the line below!
            print(f"train ppl: {perp}")
            if ((ep==5 or ep==15 or ep==28)and idx==0):
                            generated_text = complete(model, prompt, 128, sample=False)
                            gen_text.append(str(generated_text)+"\n")
                            
            generated_text = complete(model, prompt, 128, sample=False)
            print(f'----------------- epoch/batch {ep}/{idx} -----------------')
            print(prompt)
            print(generated_text)
            print(f'----------------- end generated text -------------------')

print(gen_text)

perp=[t.to("cpu").detach().numpy() for t in perp_list]
perp=np.stack(perp)

import pandas as pd
import plotly.express as px
df=pd.DataFrame(perp)
px.scatter(df)

"""EXO 2.3.A"""

print(complete(model, "THE DONKEY IN THE LION’S SKIN", 512, sample=False))

"""EXO 2.3.B"""

text=complete(model, "THE DOG IN THE LONE HOUSE", 512, sample=False)
print(text)

"""EXO 2.3.C"""

print(complete(model, "The monkey eat ", 512, sample=False))

"""EXO 2.3.D"""

print(complete(model, "Another bites to ", 512, sample=False))

"""#Model LSTM"""

# LSTM based language model
class LSTMModel(nn.Module):

    def __init__(self, num_classes, emb_dim, hidden_dim, num_layers):
        """Parameters:
        
          num_classes (int): number of input/output classes
          emb_dim (int): token embedding size
          hidden_dim (int): hidden layer size of RNNs
          num_layers (int): number of RNN layers
        """
        super().__init__()
        self.num_classes = num_classes
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        self.input_layer = nn.Embedding(num_classes, emb_dim,padding_idx=0)
        self.lstm = nn.LSTM(emb_dim, hidden_dim, num_layers)
        self.out_layer = nn.Linear(hidden_dim, num_classes)

    def forward(self, input,state):
        emb = self.input_layer(input)
        output, (hidden_state,cell_state) = self.lstm(emb, state)
        output = output.reshape(output.size(0)*output.size(1), output.size(2))  
        output = self.out_layer(output)
        
        return output, (hidden_state,cell_state)

    def init_hidden(self, bsz):
        weight = next(self.parameters())
        return weight.new_zeros(self.num_layers, bsz, self.hidden_dim)

# To be modified for LSTM...
def custom_detach(h):
    return h.detach()

"""#Decoding LSTM"""

@torch.no_grad()
def complete2(model, prompt, steps, sample=False):
    """Complete the prompt for as long as given steps using the model.
    
    Parameters:
      model: language model
      prompt (str): text segment to be completed
      steps (int): number of decoding steps.
      sample (bool): If True, sample from the model. Otherwise greedy.

    Returns:
      completed text (str)
    """
    model.eval()
    out_list = []
    
    # forward the prompt, compute prompt's ppl
    prompt_list = []
    char_prompt = list(prompt)
    for char in char_prompt:
        prompt_list.append(my_data.vocab.string_to_id[char])
    x = torch.tensor(prompt_list).to(DEVICE).unsqueeze(1)
    
    hidden_state = model.init_hidden(1)
    cell_state = model.init_hidden(1)
    logits,(hidden_state,cell_state) = model(x, (hidden_state,cell_state))
    probs = F.softmax(logits[-1], dim=-1)
        
    if sample:
        ix=torch.multinomial(probs, num_samples=1)
        #assert False
    else:
        max_p, ix = torch.topk(probs, k=1, dim=-1)

    out_list.append(my_data.vocab.id_to_string[int(ix)])
    x = ix.unsqueeze(1)
    
    # decode 
    for k in range(steps):
        logits,(hidden_state,cell_state)= model(x, (hidden_state,cell_state))
        probs = F.softmax(logits, dim=-1)
        if sample:  # sample from the distribution or take the most likely
             ix=torch.multinomial(probs, num_samples=1)   
             #assert False
        else:
            _, ix = torch.topk(probs, k=1, dim=-1)
        out_list.append(my_data.vocab.id_to_string[int(ix)])
        x = ix
    return ''.join(out_list)

learning_rate = 0.001
clipping = 1.0
embedding_size = 64
lstm_size = 2048
lstm_num_layers = 1

# vocab_size = len(module.vocab.itos)
vocab_size = len(my_data.vocab.id_to_string)
print(F"vocab size: {vocab_size}")

model2 = LSTMModel(
    num_classes=vocab_size, emb_dim=embedding_size, hidden_dim=lstm_size,
    num_layers=lstm_num_layers)
model2 = model2.to(DEVICE)
hidden = model2.init_hidden(batch_size)

loss_fn = nn.CrossEntropyLoss(ignore_index=-1)
optimizer = torch.optim.Adam(params=model2.parameters(), lr=learning_rate)

# Training

num_epoch =0
report_every = 30
prompt = "Dogs like best to"
perp=50

while perp > 1.03:
    num_epoch+=1

    
    print(f"=== start epoch {num_epoch} ===")
    
    hidden_state = model2.init_hidden(batch_size)
    cell_state = model2.init_hidden(batch_size)
    for idx in range(len(batches)):
        batch = batches[idx]
        model2.train()
        optimizer.zero_grad()

        input = batch[:-1]
        target = batch[1:].flatten()

        output,(hidden_state,cell_state)= model2(input, (hidden_state,cell_state))
        
        loss = loss_fn(output, target)
        perp=torch.exp(loss)
        perp=perp.to("cpu").detach().numpy()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model2.parameters(), clipping)
        optimizer.step()

        hidden_state=custom_detach(hidden_state)
        cell_state=custom_detach(cell_state)
        if perp < 1.03:
          break
        if idx % report_every == 0:
            # print(f"train loss: {loss.item()}")  # replace me by the line below!
            print(f"train ppl: {perp}")
            generated_text = complete2(model2, prompt, 128, sample=False)
            print(f'----------------- epoch/batch {num_epoch}/{idx} -----------------')
            print(prompt)
            print(generated_text)
            print(f'----------------- end generated text -------------------')

print("final perplexiity : ",perp,"\n")
print("final Epoch :",num_epoch)

"""#EXO 3.4.A

 Title of a fable which exists in the book.
"""

print(complete2(model2, "The Fox and the Goat", 512, sample=False))

print(complete2(model2, "The Fox and the Goat", 512, sample=True))

"""# EXO 3.4.B
title which invented,is not in the book, but similar in the style.
"""

print(complete2(model2, "The Serpent and the Cow", 512, sample=False))

print(complete2(model2, "The Serpent and the Cow", 512, sample=True))

"""#Bonus
Train model with python script
"""

# This is for Colab. Adapt the path if needed.
text_path = "/content/python.txt"

DEVICE = 'cuda'

batch_size = 32
bptt_len = 64

my_data = TextData(text_path, device=DEVICE)
batches = DataBatches(my_data, batch_size, bptt_len, pad_id=0)

learning_rate = 0.001
clipping = 1.0
embedding_size = 64
lstm_size = 2048
lstm_num_layers = 1

# vocab_size = len(module.vocab.itos)
vocab_size = len(my_data.vocab.id_to_string)
print(F"vocab size: {vocab_size}")

model2 = LSTMModel(
    num_classes=vocab_size, emb_dim=embedding_size, hidden_dim=lstm_size,
    num_layers=lstm_num_layers)
model2 = model2.to(DEVICE)
hidden = model2.init_hidden(batch_size)

loss_fn = nn.CrossEntropyLoss(ignore_index=-1)
optimizer = torch.optim.Adam(params=model2.parameters(), lr=learning_rate)

# Training

num_epoch =0
report_every = 30
prompt = "Def func "
perp=3
while perp > 1.03:
    num_epoch+=1

    
    print(f"=== start epoch {num_epoch} ===")
    
    hidden_state = model2.init_hidden(batch_size)
    cell_state = model2.init_hidden(batch_size)
    for idx in range(len(batches)):
        batch = batches[idx]
        model2.train()
        optimizer.zero_grad()

        input = batch[:-1]
        target = batch[1:].flatten()

        output,(hidden_state,cell_state)= model2(input, (hidden_state,cell_state))
        
        loss = loss_fn(output, target)
        perp=torch.exp(loss)
        perp=perp.to("cpu").detach().numpy()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model2.parameters(), clipping)
        optimizer.step()

        hidden_state=custom_detach(hidden_state)
        cell_state=custom_detach(cell_state)
        if perp < 1.03:
          break
        if idx % report_every == 0:
            # print(f"train loss: {loss.item()}")  # replace me by the line below!
            print(f"train ppl: {perp}")
            generated_text = complete2(model2, prompt, 128, sample=False)
            print(f'----------------- epoch/batch {num_epoch}/{idx} -----------------')
            print(prompt)
            print(generated_text)
            print(f'----------------- end generated text -------------------')

print("final perplexiity : ",perp,"\n")
print("final Epoch :",num_epoch)

print(complete2(model2, "print(", 512, sample=False))

print(complete2(model2, "If ", 512, sample=False))

print(complete2(model2, "while", 512, sample=False))

print(complete2(model2, "for i in range", 512, sample=False))

